### ISSUE TITLE
Bug: tabpanel drag event overlap with native drag zone

### ISSUE THREAD

**Issue by reyamir** [longbridgeapp/gpui-component#439]
I wonder is there a way to disable native drag event on tabpanel?

https://github.com/user-attachments/assets/edde7292-6877-47ef-89ca-7fe011c5841d

**Comment by huacnlee** [comment]
Here is a GPUI window limit, you must avoid the tab at the TitleBar position.

**Comment by reyamir** [comment]
Oh, thank for your feedback
