### ISSUE TITLE
Enhancement: Add unstyled DockItem

### ISSUE THREAD

**Issue by reyamir** [longbridgeapp/gpui-component#449]
I wonder can I create a `Dockitem` without any pre styled?, I mean there are no Tab or Split styles, just empty `DockItem`, so I can add it to `DockArea` left_dock or right_dock then create custom sidebar.

Currently, I need to create the left panel like this:
```rust
let left_panels = DockItem::split_with_sizes(
    Axis::Vertical,
    vec![DockItem::tabs(vec![], None, &dock_area, cx)],
    vec![None, None],
    &dock_area,
    cx,
);
```

It will be more flexible if I can create custom left panel like this:
```rust
let left_panels = DockItem::custom(< some view >)
```

It will also help to solve https://github.com/longbridgeapp/gpui-component/issues/318 and https://github.com/longbridgeapp/gpui-component/issues/430 in the future

**Comment by huacnlee** [comment]
Give me some UI example for show up what do you want to do.

**Comment by reyamir** [comment]
I think your latest commit have fixed my issue, thank for great project
https://github.com/longbridgeapp/gpui-component/commit/23d273eaf998ea4455d41c9b0c73203c0e607c6b
